spring:
  server:
    port: 8080
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: user
    password: user

  jpa:
    hibernate.ddl-auto: create

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

  security:
    user:
      name: mari
      password: mari
