spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: user
    password: user

  jpa:
    hibernate.ddl-auto: create
    #    used to export datbase schema on creaation
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
      hibernate:
        format_sql: true
    show-sql: true


  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.security: INFO

